[project]
name = "small-search-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pydantic>=2",
  "tavily-python>=0.5.0",
  "python-dotenv",
  "ollama",
  "datasets"
]

[tool.uv]
# keep a local venv per agent folder

